version: '3.8'

services:
  mysql:
    build: ./.docker/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: examplepw
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: examplepw
    volumes:
      - phpmyadmin-session:/sessions

  php:
    build: ./.docker/php
    tty: true
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

volumes:
  mysql-data:
  phpmyadmin-session:
